[dependencies]
new-base = "0.4.0"

[dev-dependencies]
base = "https://github.com/dfinity/motoko-base#c6d66bfd4d48cfa7ebb706306dd31e693da85408"
matchers = "https://github.com/kritzcreek/motoko-matchers#3dac8a071b69e4e651b25a7d9683fe831eb7cffd"

[package]
name = "motoko-snafu"
version = "0.1.0"
description = "Motoko errors with context"
repository = "https://github.com/christoph-dfinity/motoko-snafu"
keywords = [ "errors" ]
license = "Apache-2.0"

[toolchain]
wasmtime = "31.0.0"
